name: Deployment

on:
  # push:
  #   branches:
  #   - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    ####### Build steps ############

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    # - name: Run the tests
    #   run: npm test

    - name: Build
      working-directory: ./client
      run: npm run build

    ######### Deployment steps ############
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./client/dist/ s3://${{ secrets.BUCKET_NAME }} --delete

    - name: Print the selected environment name
      run: echo ${{ github.event.inputs.environment }}
      # This could be used at later stage

    # - name: Deploy to Blockchain. Could be updated later
    #   run: 

# reference: https://dev.to/johnkevinlosito/deploy-static-website-to-s3-using-github-actions-4a0e
